Type: Jupyter Notebook Extension
Compatibility: 4.x, 5.x, 6.x, 7.x
Name: WIDD
Main: main.js
Link: README.md
Description: |
  Provides a list of relevant subjects to describe the generation and analysis of social science datasets.
  Adds a button to compose a pdf-document that serves as a data documentation file.
  Helpful for social scientists interested in rigorous data analysis.
Parameters:
- name: snippets.insert_as_new_cell
  description: 'Insert WIDD-snippets as new cells, rather than appending cells'
  input_type: checkbox
  default: false
- name: snippets.sibling_selector
  description: |
    In JQuery terms: where to put the WIDD-menu in your jupyter toolbar?
    I.e. next to #help_menu or edit_menu.
  input_type: text
  default: '#help_menu'
- name: snippets.top_level_submenu_goes_left
  description: |
    Choose whether to put submenu to the left.
  input_type: checkbox
  default: true
- name: snippets.include_submenu.menu_bullets
  description: "Include our widd-menu"
  input_type: checkbox
  default: true
